### PR TITLE
QHotKey pri file has moved

### PR DESCRIPTION
**Pull request by AlMcKinlay**
It is now at vendor/vendor.pri. When I tried to install, the QHotKey folder had nothing in, and we had the new vendor directory with the pri file. 

Details [here](https://github.com/Skycoder42/QHotkey/commit/4446fe0a42a92acd94523148f6213d1383dfaf39)

### CODE REVIEW

**Comment by ArsenArsen** [comment]
While you are at it update the submodule, and I'll merge

**Comment by AlMcKinlay** [comment]
Aha, that'll be why I got the error, I didn't realise it was a submodule, I just installed QHotKey manually, and when you do that it does it in the new place. Will do that this weekend sometime.

**Comment by ArsenArsen** [comment]
I just realized, vendor/vendor.pri is a QPM made file and the current path works fine, I am closing

Also before you ask I don't mind this slight misunderstanding :)

**Comment by AlMcKinlay** [comment]
Yeah, just redid this cloning submodules and it worked as expected. It might be worth adding `--recursive` to the clone command.

**Pull request closed without merging**
