### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dm4uz3**
it works on debian tho

### CODE REVIEW

**Comment by ArsenArsen** [comment]
do it in dev

**Comment by ArsenArsen** [comment]
Reopen one in dev as I said :P

**Comment by binaryoverload** [comment]
Just re open and edit the PR... ? xD

**Comment by ArsenArsen** [comment]
That's not how it works

**Comment by binaryoverload** [comment]
the person who created the PR can click Edit and change which branch it goes into

**Pull request closed without merging**
