### PR TITLE
Add recursive to clone command

### PR DESCRIPTION
**Pull request by AlMcKinlay**
Take it if you want, throw it away if you don't. I know you said you don't mind the misunderstanding, but I feel like this would be an improvement.

### CODE REVIEW

**Comment by ArsenArsen** [comment]
Move the PR to dev.

**Comment by AlMcKinlay** [comment]
Don't need to open a new PR to change the base. Changed it now, you should be able to re-open this one.

**Comment by ArsenArsen** [comment]
The reason I did not is because I knew the conflict would happen. Fix it and squash the commits, please

**Comment by AlMcKinlay** [comment]
Oh sorry, when I changed the base, it didn't show a conflict until I reloaded the page. Will fix that up tonight.

**Comment by ArsenArsen** [comment]
Any updates?

**Comment by AlMcKinlay** [comment]
Sorry it took so long, I've been so busy. There you are.

**Pull request merged**
